---
- name: stop phantom
  shell: sudo -H -u phantom /opt/phantom/bin/stop_phantom.sh
  ignore_errors: yes
  become: yes
  tags: phantom stop

- name: start phantom
  shell: sudo -H -u phantom /opt/phantom/bin/start_phantom.sh
  ignore_errors: yes
  become: yes
  tags: phantom start

- name: phantom ip
  shell: ifconfig -a
  ignore_errors: yes
  become: yes
  tags: phantom ip